services:

  frontend:
    build:
      context: React-Frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: DotNet-Backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: myapp
      DB_USER: root
      DB_PASSWORD_FILE: /run/secrets/db_password
    depends_on:
      - db
    ports:
      - "5001:8080"
    networks:
      - app-network
    secrets:
      - db_password

  db:
    image: mysql:8.0
  
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: myapp
    volumes:
      - db-data:/var/lib/mysql
    secrets:
      - db_password

networks:
  app-network:
  

volumes:
  db-data:

secrets:
  db_password:
    file: ./db_password
