DOCKER_USERNAME: "<your docker hub username>"

images:
  - name: "{{ DOCKER_USERNAME }}/fronend-react"
    tag: "latest"
    path: "./React-Frontend"
  - name: "{{ DOCKER_USERNAME }}/backend-dotnet-api"
    tag: "latest"
    path: "./DotNet-Backend"
